/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearSummaryRouteImport } from './routes/year-summary'
import { Route as SpendingTrendsRouteImport } from './routes/spending-trends'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecurringExpensesRouteImport } from './routes/recurring-expenses'
import { Route as ProjectionRouteImport } from './routes/projection'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as SettingsAiProviderRouteImport } from './routes/settings.ai-provider'
import { Route as AiAgentIdRouteImport } from './routes/ai.$agentId'

const YearSummaryRoute = YearSummaryRouteImport.update({
  id: '/year-summary',
  path: '/year-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingTrendsRoute = SpendingTrendsRouteImport.update({
  id: '/spending-trends',
  path: '/spending-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringExpensesRoute = RecurringExpensesRouteImport.update({
  id: '/recurring-expenses',
  path: '/recurring-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionRoute = ProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const SettingsAiProviderRoute = SettingsAiProviderRouteImport.update({
  id: '/ai-provider',
  path: '/ai-provider',
  getParentRoute: () => SettingsRoute,
} as any)
const AiAgentIdRoute = AiAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ai': typeof AiRouteWithChildren
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/import': typeof ImportRoute
  '/income': typeof IncomeRoute
  '/net-worth': typeof NetWorthRoute
  '/onboarding': typeof OnboardingRoute
  '/projection': typeof ProjectionRoute
  '/recurring-expenses': typeof RecurringExpensesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/spending-trends': typeof SpendingTrendsRoute
  '/year-summary': typeof YearSummaryRoute
  '/ai/$agentId': typeof AiAgentIdRoute
  '/settings/ai-provider': typeof SettingsAiProviderRoute
  '/ai/': typeof AiIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/import': typeof ImportRoute
  '/income': typeof IncomeRoute
  '/net-worth': typeof NetWorthRoute
  '/onboarding': typeof OnboardingRoute
  '/projection': typeof ProjectionRoute
  '/recurring-expenses': typeof RecurringExpensesRoute
  '/spending-trends': typeof SpendingTrendsRoute
  '/year-summary': typeof YearSummaryRoute
  '/ai/$agentId': typeof AiAgentIdRoute
  '/settings/ai-provider': typeof SettingsAiProviderRoute
  '/ai': typeof AiIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ai': typeof AiRouteWithChildren
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/import': typeof ImportRoute
  '/income': typeof IncomeRoute
  '/net-worth': typeof NetWorthRoute
  '/onboarding': typeof OnboardingRoute
  '/projection': typeof ProjectionRoute
  '/recurring-expenses': typeof RecurringExpensesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/spending-trends': typeof SpendingTrendsRoute
  '/year-summary': typeof YearSummaryRoute
  '/ai/$agentId': typeof AiAgentIdRoute
  '/settings/ai-provider': typeof SettingsAiProviderRoute
  '/ai/': typeof AiIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/ai'
    | '/assets'
    | '/budget'
    | '/chat'
    | '/import'
    | '/income'
    | '/net-worth'
    | '/onboarding'
    | '/projection'
    | '/recurring-expenses'
    | '/settings'
    | '/spending-trends'
    | '/year-summary'
    | '/ai/$agentId'
    | '/settings/ai-provider'
    | '/ai/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/assets'
    | '/budget'
    | '/chat'
    | '/import'
    | '/income'
    | '/net-worth'
    | '/onboarding'
    | '/projection'
    | '/recurring-expenses'
    | '/spending-trends'
    | '/year-summary'
    | '/ai/$agentId'
    | '/settings/ai-provider'
    | '/ai'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/ai'
    | '/assets'
    | '/budget'
    | '/chat'
    | '/import'
    | '/income'
    | '/net-worth'
    | '/onboarding'
    | '/projection'
    | '/recurring-expenses'
    | '/settings'
    | '/spending-trends'
    | '/year-summary'
    | '/ai/$agentId'
    | '/settings/ai-provider'
    | '/ai/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AiRoute: typeof AiRouteWithChildren
  AssetsRoute: typeof AssetsRoute
  BudgetRoute: typeof BudgetRoute
  ChatRoute: typeof ChatRoute
  ImportRoute: typeof ImportRoute
  IncomeRoute: typeof IncomeRoute
  NetWorthRoute: typeof NetWorthRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectionRoute: typeof ProjectionRoute
  RecurringExpensesRoute: typeof RecurringExpensesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SpendingTrendsRoute: typeof SpendingTrendsRoute
  YearSummaryRoute: typeof YearSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/year-summary': {
      id: '/year-summary'
      path: '/year-summary'
      fullPath: '/year-summary'
      preLoaderRoute: typeof YearSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending-trends': {
      id: '/spending-trends'
      path: '/spending-trends'
      fullPath: '/spending-trends'
      preLoaderRoute: typeof SpendingTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring-expenses': {
      id: '/recurring-expenses'
      path: '/recurring-expenses'
      fullPath: '/recurring-expenses'
      preLoaderRoute: typeof RecurringExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projection': {
      id: '/projection'
      path: '/projection'
      fullPath: '/projection'
      preLoaderRoute: typeof ProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/settings/ai-provider': {
      id: '/settings/ai-provider'
      path: '/ai-provider'
      fullPath: '/settings/ai-provider'
      preLoaderRoute: typeof SettingsAiProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/ai/$agentId': {
      id: '/ai/$agentId'
      path: '/$agentId'
      fullPath: '/ai/$agentId'
      preLoaderRoute: typeof AiAgentIdRouteImport
      parentRoute: typeof AiRoute
    }
  }
}

interface AiRouteChildren {
  AiAgentIdRoute: typeof AiAgentIdRoute
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiAgentIdRoute: AiAgentIdRoute,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface SettingsRouteChildren {
  SettingsAiProviderRoute: typeof SettingsAiProviderRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAiProviderRoute: SettingsAiProviderRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AiRoute: AiRouteWithChildren,
  AssetsRoute: AssetsRoute,
  BudgetRoute: BudgetRoute,
  ChatRoute: ChatRoute,
  ImportRoute: ImportRoute,
  IncomeRoute: IncomeRoute,
  NetWorthRoute: NetWorthRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectionRoute: ProjectionRoute,
  RecurringExpensesRoute: RecurringExpensesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SpendingTrendsRoute: SpendingTrendsRoute,
  YearSummaryRoute: YearSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
