/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CarRouteImport } from './routes/car'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WealthIndexRouteImport } from './routes/wealth.index'
import { Route as SpendingIndexRouteImport } from './routes/spending.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as CarIndexRouteImport } from './routes/car.index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as WealthWhereToPutYourMoneyRouteImport } from './routes/wealth.where-to-put-your-money'
import { Route as WealthNetWorthRouteImport } from './routes/wealth.net-worth'
import { Route as WealthAssetsRouteImport } from './routes/wealth.assets'
import { Route as WealthAccountsRouteImport } from './routes/wealth.accounts'
import { Route as SpendingTransactionsRouteImport } from './routes/spending.transactions'
import { Route as SpendingRecurringRouteImport } from './routes/spending.recurring'
import { Route as SpendingIncomeRouteImport } from './routes/spending.income'
import { Route as SpendingBudgetRouteImport } from './routes/spending.budget'
import { Route as SettingsAiProviderRouteImport } from './routes/settings.ai-provider'
import { Route as InsightsYearSummaryRouteImport } from './routes/insights.year-summary'
import { Route as InsightsTrendsRouteImport } from './routes/insights.trends'
import { Route as InsightsProjectionRouteImport } from './routes/insights.projection'
import { Route as CarGarageRouteImport } from './routes/car.garage'
import { Route as AiAgentIdRouteImport } from './routes/ai.$agentId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRoute = CarRouteImport.update({
  id: '/car',
  path: '/car',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WealthIndexRoute = WealthIndexRouteImport.update({
  id: '/wealth/',
  path: '/wealth/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingIndexRoute = SpendingIndexRouteImport.update({
  id: '/spending/',
  path: '/spending/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarIndexRoute = CarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarRoute,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const WealthWhereToPutYourMoneyRoute =
  WealthWhereToPutYourMoneyRouteImport.update({
    id: '/wealth/where-to-put-your-money',
    path: '/wealth/where-to-put-your-money',
    getParentRoute: () => rootRouteImport,
  } as any)
const WealthNetWorthRoute = WealthNetWorthRouteImport.update({
  id: '/wealth/net-worth',
  path: '/wealth/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const WealthAssetsRoute = WealthAssetsRouteImport.update({
  id: '/wealth/assets',
  path: '/wealth/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const WealthAccountsRoute = WealthAccountsRouteImport.update({
  id: '/wealth/accounts',
  path: '/wealth/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingTransactionsRoute = SpendingTransactionsRouteImport.update({
  id: '/spending/transactions',
  path: '/spending/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingRecurringRoute = SpendingRecurringRouteImport.update({
  id: '/spending/recurring',
  path: '/spending/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingIncomeRoute = SpendingIncomeRouteImport.update({
  id: '/spending/income',
  path: '/spending/income',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingBudgetRoute = SpendingBudgetRouteImport.update({
  id: '/spending/budget',
  path: '/spending/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiProviderRoute = SettingsAiProviderRouteImport.update({
  id: '/ai-provider',
  path: '/ai-provider',
  getParentRoute: () => SettingsRoute,
} as any)
const InsightsYearSummaryRoute = InsightsYearSummaryRouteImport.update({
  id: '/insights/year-summary',
  path: '/insights/year-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsTrendsRoute = InsightsTrendsRouteImport.update({
  id: '/insights/trends',
  path: '/insights/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsProjectionRoute = InsightsProjectionRouteImport.update({
  id: '/insights/projection',
  path: '/insights/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const CarGarageRoute = CarGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => CarRoute,
} as any)
const AiAgentIdRoute = AiAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/car': typeof CarRouteWithChildren
  '/chat': typeof ChatRoute
  '/import': typeof ImportRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ai/$agentId': typeof AiAgentIdRoute
  '/car/garage': typeof CarGarageRoute
  '/insights/projection': typeof InsightsProjectionRoute
  '/insights/trends': typeof InsightsTrendsRoute
  '/insights/year-summary': typeof InsightsYearSummaryRoute
  '/settings/ai-provider': typeof SettingsAiProviderRoute
  '/spending/budget': typeof SpendingBudgetRoute
  '/spending/income': typeof SpendingIncomeRoute
  '/spending/recurring': typeof SpendingRecurringRoute
  '/spending/transactions': typeof SpendingTransactionsRoute
  '/wealth/accounts': typeof WealthAccountsRoute
  '/wealth/assets': typeof WealthAssetsRoute
  '/wealth/net-worth': typeof WealthNetWorthRoute
  '/wealth/where-to-put-your-money': typeof WealthWhereToPutYourMoneyRoute
  '/ai/': typeof AiIndexRoute
  '/car/': typeof CarIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/spending/': typeof SpendingIndexRoute
  '/wealth/': typeof WealthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/import': typeof ImportRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/ai/$agentId': typeof AiAgentIdRoute
  '/car/garage': typeof CarGarageRoute
  '/insights/projection': typeof InsightsProjectionRoute
  '/insights/trends': typeof InsightsTrendsRoute
  '/insights/year-summary': typeof InsightsYearSummaryRoute
  '/settings/ai-provider': typeof SettingsAiProviderRoute
  '/spending/budget': typeof SpendingBudgetRoute
  '/spending/income': typeof SpendingIncomeRoute
  '/spending/recurring': typeof SpendingRecurringRoute
  '/spending/transactions': typeof SpendingTransactionsRoute
  '/wealth/accounts': typeof WealthAccountsRoute
  '/wealth/assets': typeof WealthAssetsRoute
  '/wealth/net-worth': typeof WealthNetWorthRoute
  '/wealth/where-to-put-your-money': typeof WealthWhereToPutYourMoneyRoute
  '/ai': typeof AiIndexRoute
  '/car': typeof CarIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/spending': typeof SpendingIndexRoute
  '/wealth': typeof WealthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/car': typeof CarRouteWithChildren
  '/chat': typeof ChatRoute
  '/import': typeof ImportRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ai/$agentId': typeof AiAgentIdRoute
  '/car/garage': typeof CarGarageRoute
  '/insights/projection': typeof InsightsProjectionRoute
  '/insights/trends': typeof InsightsTrendsRoute
  '/insights/year-summary': typeof InsightsYearSummaryRoute
  '/settings/ai-provider': typeof SettingsAiProviderRoute
  '/spending/budget': typeof SpendingBudgetRoute
  '/spending/income': typeof SpendingIncomeRoute
  '/spending/recurring': typeof SpendingRecurringRoute
  '/spending/transactions': typeof SpendingTransactionsRoute
  '/wealth/accounts': typeof WealthAccountsRoute
  '/wealth/assets': typeof WealthAssetsRoute
  '/wealth/net-worth': typeof WealthNetWorthRoute
  '/wealth/where-to-put-your-money': typeof WealthWhereToPutYourMoneyRoute
  '/ai/': typeof AiIndexRoute
  '/car/': typeof CarIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/spending/': typeof SpendingIndexRoute
  '/wealth/': typeof WealthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/car'
    | '/chat'
    | '/import'
    | '/maintenance'
    | '/onboarding'
    | '/settings'
    | '/ai/$agentId'
    | '/car/garage'
    | '/insights/projection'
    | '/insights/trends'
    | '/insights/year-summary'
    | '/settings/ai-provider'
    | '/spending/budget'
    | '/spending/income'
    | '/spending/recurring'
    | '/spending/transactions'
    | '/wealth/accounts'
    | '/wealth/assets'
    | '/wealth/net-worth'
    | '/wealth/where-to-put-your-money'
    | '/ai/'
    | '/car/'
    | '/insights/'
    | '/settings/'
    | '/spending/'
    | '/wealth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/import'
    | '/maintenance'
    | '/onboarding'
    | '/ai/$agentId'
    | '/car/garage'
    | '/insights/projection'
    | '/insights/trends'
    | '/insights/year-summary'
    | '/settings/ai-provider'
    | '/spending/budget'
    | '/spending/income'
    | '/spending/recurring'
    | '/spending/transactions'
    | '/wealth/accounts'
    | '/wealth/assets'
    | '/wealth/net-worth'
    | '/wealth/where-to-put-your-money'
    | '/ai'
    | '/car'
    | '/insights'
    | '/settings'
    | '/spending'
    | '/wealth'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/car'
    | '/chat'
    | '/import'
    | '/maintenance'
    | '/onboarding'
    | '/settings'
    | '/ai/$agentId'
    | '/car/garage'
    | '/insights/projection'
    | '/insights/trends'
    | '/insights/year-summary'
    | '/settings/ai-provider'
    | '/spending/budget'
    | '/spending/income'
    | '/spending/recurring'
    | '/spending/transactions'
    | '/wealth/accounts'
    | '/wealth/assets'
    | '/wealth/net-worth'
    | '/wealth/where-to-put-your-money'
    | '/ai/'
    | '/car/'
    | '/insights/'
    | '/settings/'
    | '/spending/'
    | '/wealth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRouteWithChildren
  CarRoute: typeof CarRouteWithChildren
  ChatRoute: typeof ChatRoute
  ImportRoute: typeof ImportRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  InsightsProjectionRoute: typeof InsightsProjectionRoute
  InsightsTrendsRoute: typeof InsightsTrendsRoute
  InsightsYearSummaryRoute: typeof InsightsYearSummaryRoute
  SpendingBudgetRoute: typeof SpendingBudgetRoute
  SpendingIncomeRoute: typeof SpendingIncomeRoute
  SpendingRecurringRoute: typeof SpendingRecurringRoute
  SpendingTransactionsRoute: typeof SpendingTransactionsRoute
  WealthAccountsRoute: typeof WealthAccountsRoute
  WealthAssetsRoute: typeof WealthAssetsRoute
  WealthNetWorthRoute: typeof WealthNetWorthRoute
  WealthWhereToPutYourMoneyRoute: typeof WealthWhereToPutYourMoneyRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  SpendingIndexRoute: typeof SpendingIndexRoute
  WealthIndexRoute: typeof WealthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car': {
      id: '/car'
      path: '/car'
      fullPath: '/car'
      preLoaderRoute: typeof CarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wealth/': {
      id: '/wealth/'
      path: '/wealth'
      fullPath: '/wealth/'
      preLoaderRoute: typeof WealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending/': {
      id: '/spending/'
      path: '/spending'
      fullPath: '/spending/'
      preLoaderRoute: typeof SpendingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/': {
      id: '/car/'
      path: '/'
      fullPath: '/car/'
      preLoaderRoute: typeof CarIndexRouteImport
      parentRoute: typeof CarRoute
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/wealth/where-to-put-your-money': {
      id: '/wealth/where-to-put-your-money'
      path: '/wealth/where-to-put-your-money'
      fullPath: '/wealth/where-to-put-your-money'
      preLoaderRoute: typeof WealthWhereToPutYourMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wealth/net-worth': {
      id: '/wealth/net-worth'
      path: '/wealth/net-worth'
      fullPath: '/wealth/net-worth'
      preLoaderRoute: typeof WealthNetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wealth/assets': {
      id: '/wealth/assets'
      path: '/wealth/assets'
      fullPath: '/wealth/assets'
      preLoaderRoute: typeof WealthAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wealth/accounts': {
      id: '/wealth/accounts'
      path: '/wealth/accounts'
      fullPath: '/wealth/accounts'
      preLoaderRoute: typeof WealthAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending/transactions': {
      id: '/spending/transactions'
      path: '/spending/transactions'
      fullPath: '/spending/transactions'
      preLoaderRoute: typeof SpendingTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending/recurring': {
      id: '/spending/recurring'
      path: '/spending/recurring'
      fullPath: '/spending/recurring'
      preLoaderRoute: typeof SpendingRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending/income': {
      id: '/spending/income'
      path: '/spending/income'
      fullPath: '/spending/income'
      preLoaderRoute: typeof SpendingIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending/budget': {
      id: '/spending/budget'
      path: '/spending/budget'
      fullPath: '/spending/budget'
      preLoaderRoute: typeof SpendingBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai-provider': {
      id: '/settings/ai-provider'
      path: '/ai-provider'
      fullPath: '/settings/ai-provider'
      preLoaderRoute: typeof SettingsAiProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/insights/year-summary': {
      id: '/insights/year-summary'
      path: '/insights/year-summary'
      fullPath: '/insights/year-summary'
      preLoaderRoute: typeof InsightsYearSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/trends': {
      id: '/insights/trends'
      path: '/insights/trends'
      fullPath: '/insights/trends'
      preLoaderRoute: typeof InsightsTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/projection': {
      id: '/insights/projection'
      path: '/insights/projection'
      fullPath: '/insights/projection'
      preLoaderRoute: typeof InsightsProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/garage': {
      id: '/car/garage'
      path: '/garage'
      fullPath: '/car/garage'
      preLoaderRoute: typeof CarGarageRouteImport
      parentRoute: typeof CarRoute
    }
    '/ai/$agentId': {
      id: '/ai/$agentId'
      path: '/$agentId'
      fullPath: '/ai/$agentId'
      preLoaderRoute: typeof AiAgentIdRouteImport
      parentRoute: typeof AiRoute
    }
  }
}

interface AiRouteChildren {
  AiAgentIdRoute: typeof AiAgentIdRoute
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiAgentIdRoute: AiAgentIdRoute,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface CarRouteChildren {
  CarGarageRoute: typeof CarGarageRoute
  CarIndexRoute: typeof CarIndexRoute
}

const CarRouteChildren: CarRouteChildren = {
  CarGarageRoute: CarGarageRoute,
  CarIndexRoute: CarIndexRoute,
}

const CarRouteWithChildren = CarRoute._addFileChildren(CarRouteChildren)

interface SettingsRouteChildren {
  SettingsAiProviderRoute: typeof SettingsAiProviderRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAiProviderRoute: SettingsAiProviderRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRouteWithChildren,
  CarRoute: CarRouteWithChildren,
  ChatRoute: ChatRoute,
  ImportRoute: ImportRoute,
  MaintenanceRoute: MaintenanceRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRouteWithChildren,
  InsightsProjectionRoute: InsightsProjectionRoute,
  InsightsTrendsRoute: InsightsTrendsRoute,
  InsightsYearSummaryRoute: InsightsYearSummaryRoute,
  SpendingBudgetRoute: SpendingBudgetRoute,
  SpendingIncomeRoute: SpendingIncomeRoute,
  SpendingRecurringRoute: SpendingRecurringRoute,
  SpendingTransactionsRoute: SpendingTransactionsRoute,
  WealthAccountsRoute: WealthAccountsRoute,
  WealthAssetsRoute: WealthAssetsRoute,
  WealthNetWorthRoute: WealthNetWorthRoute,
  WealthWhereToPutYourMoneyRoute: WealthWhereToPutYourMoneyRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  SpendingIndexRoute: SpendingIndexRoute,
  WealthIndexRoute: WealthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
